### ISSUE TITLE
Sistesis Gestion de Desarrollo de Software en Webniar

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/actividad-3-sintesis-Arnold-Js#1]
[Sintesis-GPSW.pdf](https://github.com/user-attachments/files/16830869/Sintesis-GPSW.pdf)

**Comment by Rosa218** [comment]
Calificación: 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
